TEXT_COLUMN = 'review'
LABEL_COLUMN = 'sentiment'
GENERATIONS = 25
N_POPULATION = 3
PROB_MUTATION = 0.2
MAX_SAMPLE_SIZE_DS = 150
NEURONS_CHANGE_FACTOR = 0.8 # reduce neurons by 20% each layer
DS_PATH = 'datasets/IMDB_Dataset.csv'