GENERATIONS = 1
N_POPULATION = 3
MAX_SAMPLE_SIZE_DS = 20
DS_PATH = 'datasets/IMDB_Dataset.csv'
LOG_FILE_DIR = 'logs_test'

[FROZEN_PARAMETERS] # used for testing: freeze parameters to a specific value
    n_layers = 0