GENERATIONS = 100
N_POPULATION = 10
MAX_SAMPLE_SIZE_DS = 200 # shall be 150
DS_PATH = 'datasets/IMDB_Dataset.csv'
LOG_FILE_DIR = 'logs_test'

[FROZEN_PARAMETERS] # used for testing: freeze parameters to a specific value
    #emb_model_name = 'bert-base-uncased'
    #emb_comb_strategy = 'concat'