GENERATIONS = 100
N_POPULATION = 10
MAX_SAMPLE_SIZE_DS = 200 # shall be 150
DS_PATH = 'datasets/IMDB_Dataset.csv'
LOG_FILE_DIR = 'logs_test'
CLEAR_CACHE = false
[FROZEN_PARAMETERS] # used for testing: freeze parameters to a specific value
    emb_model_name="intfloat/e5-large-v2"
    emb_comb_strategy="concat"
    preprop_rem_stopwords = false
    preprop_word_normalization = "stemming"
    preprop_lowercasing = true
    preprop_remove_punctuation = true
    preprop_TFIDF_word_removal = true